### ISSUE TITLE
app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by RaHuLMeghani24** [snyk/snyk-code-review-exercise#13]
Hello Team, I have an interview scheduled for the 1st of August. I cloned the typescript-recurisve-deps branch and tried to run it locally. I did npm install first and then npm start. But I get this error after doing npm start:
![image](https://user-images.githubusercontent.com/47320917/181042223-d9b82987-c90d-43be-8f3d-76c6561f787a.png)

It would be a great help if anyone could help me with it.  I tried to look for the error on StackOverflow but it still persists.
Edit: nodemon is installed locally. I believe this error occurs due to the following line of code in package.json file:
![image](https://user-images.githubusercontent.com/47320917/181046855-49224aa7-5106-4bd7-a5e3-258c93434398.png)

**Comment by georgeharley** [comment]
@RaHuLMeghani24 I do not see this error when I try to repeat your steps using npm 6.14.15 on macOS Monterey ...
```bash
$ npm --version
6.14.15
$ node --version
v14.17.6
```

```bash
$ npm install

> nodemon@2.0.12 postinstall /Users/georgeharley/code/workspace/snyk-code-review-exercise/node_modules/nodemon
> node bin/postinstall || exit 0

added 709 packages from 418 contributors and audited 710 packages in 12.188s

62 packages are looking for funding
  run `npm fund` for details

found 29 vulnerabilities (2 moderate, 18 high, 9 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm start

> snyk-code-review-exercise@1.0.0 start /Users/georgeharley/code/workspace/snyk-code-review-exercise
> nodemon --watch src --ext .ts --exec "$(npm bin)/ts-node ./src/main.ts"

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `/Users/georgeharley/code/workspace/snyk-code-review-exercise/node_modules/.bin/ts-node ./src/main.ts`
Server listening on http://127.0.0.1:3000

. . .

```

What version of npm are you using?

**Comment by RaHuLMeghani24** [comment]
@georgeharley Thank you for reaching out. I am using npm version-8.1.2 and node version-16.13.2 on windows machine
![image](https://user-images.githubusercontent.com/47320917/181051020-8e572100-d8d5-4f7c-9d6a-6259a754b548.png)

**Comment by georgeharley** [comment]
@RaHuLMeghani24 Yes, looks like the node and npm versions might not be behind this. I just switched to using node version 16.13.2 and npm 8.1.2 (i.e. your original versions) and everything still works on my machine. 

I am using the bash shell in my macOS terminal and if I just run `echo $(npm bin)/ts-node ./src/main.ts` from the root of the repo clone then it also works OK...
```bash
$ echo $(npm bin)/ts-node ./src/main.ts
/Users/georgeharley/code/workspace/snyk-code-review-exercise/node_modules/.bin/ts-node ./src/main.ts
```

**Comment by RaHuLMeghani24** [comment]
@georgeharley Thank you so much for sharing that terminal output. It makes sense cause in linux and MacOS, we use $ notation for variables. 

By following the output, I modified my package.json file and added the entire path:
![image](https://user-images.githubusercontent.com/47320917/181091754-2b953522-cd6f-4380-b38c-a725be676485.png)

It is working now. Thank you for your help. You can close this issue.
